name: Send News

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'  # Запуск каждые 5 часов

jobs:
  send_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug files
        run: ls -R && pwd

      - name: Install dependencies
        run: pip install openai

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python send_news.py
