name: Send News

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'  # Запуск каждые 5 часов

jobs:
  send_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug files
        run: ls -R

      - name: Check working directory
        run: pwd

      - name: Set permissions
        run: chmod +x send_news.py

      - name: Install Python and Pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run script
        run: python3 send_news.py
