name: Send News

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'  # Раз в 5 часов

jobs:
  send_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug files  # 🔍 Проверяем файлы
        run: ls -R

      - name: Check working directory  # 📌 Проверяем текущую папку
        run: pwd

      - name: Set permissions for send_news.py  # 🛠️ Даем права на запуск
        run: chmod +x send_news.py

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python send_news.py
